# Copyright (c) 2024 Robert Bosch GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

color_dict = {
    "HHKEightLocalDefaultConfigGPModelMarginalizedConfigMAPInitializedActive": "red",
    "HHKEightLocalDefaultConfigBasicGPModelMarginalizedConfigActive": "red",
    "HHKEightLocalDefaultConfigGPModelMarginalizedConfigMAPInitializedRandom": "navy",
    "HHKEightLocalDefaultConfigBasicGPModelMarginalizedConfigRandom": "navy",
    "TreedGP": "green",
    "CHActiveSevenHp": "navy",
    "HHKEightLocalDefaultConfigBasicGPModelConfigActive": "navy",
    "RBFActiveML": "orange",
    "WaMIGPActive": "black",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigObjectBOExpectedImprovementConfig": "red",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEI": "red",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigGreedyHeuristicConfig": "black",
    "BasicHellingerKernelKernelConfigObjectBOExpectedImprovementConfig": "green",
    "BasicHellingerKernelKernelVirtualFromDataConfig": "green",
    "BasicHellingerKernelKernelFlatInitialConfig": "green",
    "KernelGrammarSubtreeKernelConfigEI": "orange",
    "KernelGrammarElementaryPathKernelConfigEI": "brown",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEIFewerCandidates": "blue",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEIFewerNewMoreInitial": "pink",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEIMoreCandidates": "red",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigDeeperSearch": "red",
    "SumSubtreeAndElementaryPathKernelGrammarKernelExtenseBest": "red",
    "OptimalTransportGrammarKernelConfigEI": "green",
    "SumStaticSubtreeElementaryPathGrammarKernelConfigEI": "blue",
    "TreeBasedOTGrammarKernelConfigEI": "brown",
    "OptimalTransportGrammarKernelConfigGreedyHeuristicConfig": "black",
    "JacobianRegularizedIResnetKernelBasicGPModelConfig": "green",
    "JacobianRegularizedk100IResnetKernelBasicGPModelExtenseConfig": "navy",
    "OTWeightedDimsExtendedGrammarKernelConfigEI": "red",
    "ebe3e26cba234cb2b2768bf76231a58entrain300withnoiseprior": "red",
    "ebe3e26cba234cb2b2768bf76231a58entrain100withnoiseprior": "red",
    "OTWeightedDimsEvidenceWithNoisePrior": "red",
    "OTWeightedDimsExtendedGrammarKernelConfigEIEvOpt": "navy",
    "OTWeightedDimsExtendedGrammarKernelConfigGreedyHeuristicConfig": "black",
    "BasicHellingerKernelKernelConfigEI": "green",
    "HellingerKernelKernelSobolVirtualPointsEI": "green",
    "OTWeightedDimsExtendedGrammarKernelConfigObjectBOExpectedImprovementEAConfigEvOpt": "red",
    "BaseGreedyKernelSearchConfig": "black",
    "GreedyKernelSearchBaseInitialConfig": "black",
    "GreedyKernelSearchBaseInitialConfigFewerSteps": "black",
    "GreedyKernelSearch6NeighboursLimitedConfig": "orange",
    "GreedyKernelSearchNumNeighboursLimitedConfig": "orange",
    "OTWeightedDimsExtendedGrammarKernelConfigEAFewerSteps": "red",
    "OTWeightedDimsExtendedGrammarKernelConfigObjectBOExpectedImprovementEAFewerStepsConfigEvOpt": "red",
    "OTWeightedDimsExtendedGrammarKernelConfigObjectBOExpectedImprovementEAFlatWideConfigEvOpt": "red",
    "TreeGEPEvoluationaryOptimizerConfig": "navy",
    "TreeGEPEvolutionaryOptimizerConfig": "navy",
    "TreeGEPEvolutionaryOptimizerConfigRepeat3": "navy",
    "TreeGEPsmallerDepth": "navy",
}


name_dict = {
    "HHKEightLocalDefaultConfigGPModelMarginalizedConfigMAPInitializedActive": "HHK - HMC (Active)",
    "CHActiveSevenHp": "HHK - MAP (Active)",
    "HHKEightLocalDefaultConfigBasicGPModelMarginalizedConfigActive": "HHK - HMC (Active)",
    "HHKEightLocalDefaultConfigGPModelMarginalizedConfigMAPInitializedRandom": "HHK - HMC (Random)",
    "HHKEightLocalDefaultConfigBasicGPModelMarginalizedConfigRandom": "HHK - HMC (Random)",
    "HHKEightLocalDefaultConfigBasicGPModelConfigActive": "HHK - MAP (Active)",
    "TreedGP": "Treed GP (Active)",
    "RBFActiveML": "RBF (Active)",
    "WaMIGPActive": "WaMI GP (Active)",
    "BasicRBFConfigBasicGPModelConfig": "RBF - ML",
    "BasicMatern52ConfigBasicGPModelConfig": "Matern52 - ML",
    "HHKFourLocalDefaultConfigBasicGPModelConfig": "HHK Four - MAP",
    "BasicInvertibleResnetKernelConfigBasicGPModelConfig": "i-Resnet Kernel - ML",
    "FullyDependendInvertibleResnetKernelConfigBasicGPModelConfig": "i-Resnet Kernel",
    "BasicMKNConfigBasicSparseGPModelConfig": "NKN (Sparse)",
    "HHKEightLocalDefaultConfigBasicGPModelConfig": "HHK Eight - MAP",
    "SmallDeepKernelWithPriorConfigBasicGPModelConfig": "DKL (small) - MAP",
    "CurlRegularizedIResnetKernelConfigBasicGPModelConfig20repeats": "i-Resnet (Curl,20 rep)",
    "CurlRegularizedIResnetKernelConfigBasicGPModelConfig": "i-Resnet (Curl,5 rep)",
    "CurlStrongRegularizedIResnetKernelConfigBasicGPModelConfig": "i-Resnet (Curl,stronger)",
    "DeepKernelWithPriorConfigBasicGPModelConfig": "DKL - MAP",
    "BasicMatern52WithPriorConfigGPModelMarginalizedConfigMAPInitialized": "Matern52 - HMC",
    "CurlRegularizedIResnetKernelConfigGPModelMarginalizedConfigMAPInitialized": "Curl i-ResNet - HMC (MAP init)",
    "SmallDeepKernelWithPriorConfigGPModelMarginalizedConfigMAPInitialized": "DKL (small) - HMC",
    "CurlRegularizedIResnetKernelConfigGPModelMarginalizedConfigMoreSamplesMoreThinningConfig": "Curl i-ResNet - HMC (extense)",
    "CurlRegularizedIResnetKernelConfigBasicGPModelMarginalizedConfig": "Curl i-ResNet - HMC",
    "CurlRegularizedIResnetKernelConfigGPModelExtenseOptimization": "i-Resnet (Curl,extense)",
    "CurlRegularizedIResnetKernelKConstrainedConfigGPModelExtenseOptimization": "i-Resnet (Curl,k-constraint)",
    "BasicMatern52ConfigSparseGPModel700IPConfig": "Matern52, IP",
    "CurlRegularizedIResnetKernelKConstrainedConfigSparseGPModel700IPConfig": "i-Resnet (Curl,k,IP)",
    "CurlRegularizedIResnetKernelKConstrainedConfigSparseGPModel700IPExtenseConfig": "i-Resnet (Curl,k,IP,ext)",
    "BasicMatern52ConfigSparseGPModel700IPExtenseConfig": "Matern52, IP",
    "DeepKernelWithPriorConfigSparseGPModel700IPConfig": "DKL - IP",
    "FullyDependendInvertibleResnetKernelConfigSparseGPModel700IPConfig": "i-Resnet (IP)",
    "SmallDeepKernelWithPriorConfigSparseGPModel700IPConfig": "DKL (small,IP)",
    "BasicRBFConfigDeepGPConfig": "DeepGP",
    "BasicBayesianHMEConfig": "Bayesian HME",
    "CurlRegularizedIResnetKernelKConstrainedLinearTransformedConfigGPModelExtenseOptimization": "i-Resnet (Curl,k,linTrans)",
    "CurlRegularizedIResnetKernelKConstrainedBoundedLinearTransformedConfigGPModelExtenseOptimization": "i-Resnet (Curl,k,linTrans,b)",
    "CurlRegularizedIResnetKernelKConstrainedGivensTransformedConfigGPModelExtenseOptimization": "i-Resnet (Curl,k,linTrans,g)",
    "CurlDiffRegularizedIResnetKernelKConstrainedConfigGPModelExtenseOptimization": "i-Resnet (Curl,k,diff)",
    "CurlRegularizedIResnetKernelKConstrainedConfigGPRAdamWithValidationSet": "i-Resnet (Curl,k,val)",
    "FullyDependendInvertibleResnetKernelConfigGPRAdamWithValidationSet": "i-Resnet (val,RMSE)",
    "FullyDependendInvertibleResnetKernelConfigGPRAdamWithValidationSetNLL": "i-Resnet (val,NLL)",
    "FullyDependendInvertibleResnetKernelConfigGPModelMarginalizedConfigMAPInitialized": "i-Resnet - HMC (MAP init)",
    "FullyDependendShorterInvertibleResnetKernelBasicGPModelConfig": "i-Resnet (shorter)",
    "CurlRegularizedIResnetKernelKConstrainedConfigBasicGPModelConfigPredVarActiveLearnerConfig": "i-Resnet (Curl), Active",
    "FullyDependendInvertibleResnetKernelConfigBasicGPModelConfigPredVarActiveLearnerConfig": "i-Resnet, Active",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigObjectBOExpectedImprovementConfig": "SumTreeKernelKernel",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEI": "SumTreeKernelKernel",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigGreedyHeuristicConfig": "Greedy Search",
    "SumStaticSubtreeElementaryPathGrammarKernelConfigGreedyHeuristicConfig": "Greedy Search",
    "BasicHellingerKernelKernelConfigObjectBOExpectedImprovementConfig": "HellingerKernel",
    "KernelGrammarSubtreeKernelConfigEI": "SubtreeKernelKernel",
    "KernelGrammarElementaryPathKernelConfigEI": "ElementaryPathKernelKernel",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEIFewerCandidates": "SumTreeKernelKernel (Fewer)",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEIFewerNewMoreInitial": "SumTreeKernelKernel (Fewer,More initial)",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigEIMoreCandidates": "SumTreeKernelKernel (More)",
    "SumSubtreeAndElementaryPathKernelGrammarKernelConfigDeeperSearch": "SumTreeKernelKernel (Deeper Search)",
    "SumSubtreeAndElementaryPathKernelGrammarKernelExtenseBest": "SumTreeKernelKernel",
    "SumStaticSubtreeElementaryPathGrammarKernelConfigEI": "SumStaticKernelKernel",
    "OptimalTransportGrammarKernelConfigEI": "OT Kernel-Kernel",
    "OTWeightedDimsExtendedGrammarKernelConfigObjectBOExpectedImprovementEAConfigEvOpt": "SOT Kernel (ours)",
    "TreeBasedOTGrammarKernelConfigEI": "Tree-based OT Kernel",
    "OptimalTransportGrammarKernelConfigGreedyHeuristicConfig": "Greedy Search",
    "JacobianRegularizedIResnetKernelBasicGPModelConfig": "i-Resnet (Jacobian,k)",
    "JacobianRegularizedk100IResnetKernelBasicGPModelExtenseConfig": "i-Resnet (Jacobian,k=100)",
    "OTWeightedDimsExtendedGrammarKernelConfigEI": "SOT Kernel (ours)",
    "ebe3e26cba234cb2b2768bf76231a58entrain300withnoiseprior": "SOT Kernel (ours)",
    "ebe3e26cba234cb2b2768bf76231a58entrain100withnoiseprior": "SOT Kernel (ours)",
    "OTWeightedDimsEvidenceWithNoisePrior": "SOT Kernel (ours)",
    "OTWeightedDimsExtendedGrammarKernelConfigEIEvOpt": "SOT Kernel (ours)",
    "OTWeightedDimsExtendedGrammarKernelConfigGreedyHeuristicConfig": "Greedy Search",
    "BasicHellingerKernelKernelConfigEI": "Hellinger Kernel",
    "BasicHellingerKernelKernelVirtualFromDataConfig": "Hellinger Kernel",
    "HellingerKernelKernelSobolVirtualPointsEI": "Hellinger Kernel",
    "BasicHellingerKernelKernelFlatInitialConfig": "Hellinger Kernel",
    "BaseGreedyKernelSearchConfig": "Greedy search",
    "GreedyKernelSearchBaseInitialConfigFewerSteps": "Greedy search",
    "GreedyKernelSearchBaseInitialConfig": "Greedy search",
    "GreedyKernelSearch6NeighboursLimitedConfig": "Greedy search (stochastic)",
    "GreedyKernelSearchNumNeighboursLimitedConfig": "Greedy search (stochastic)",
    "OTWeightedDimsExtendedGrammarKernelConfigEAFewerSteps": "SOT Kernel (ours)",
    "OTWeightedDimsExtendedGrammarKernelConfigObjectBOExpectedImprovementEAFewerStepsConfigEvOpt": "SOT Kernel (ours)",
    "OTWeightedDimsExtendedGrammarKernelConfigObjectBOExpectedImprovementEAFlatWideConfigEvOpt": "SOT Kernel (ours)",
    "TreeGEPEvoluationaryOptimizerConfig": "Tree-GEP",
    "TreeGEPsmallerDepth": "Tree-GEP",
    "TreeGEPEvolutionaryOptimizerConfigRepeat3": "Tree-GEP",
    "TreeGEPEvolutionaryOptimizerConfig": "Tree-GEP",
    "MLPWithPriorDeepKernelConfigGPRAdamWithValidationSet": "DKL",
    "BasicWamiConfigBasicGPModelConfig": "WaMI",
}
